"""rename user_name to username

Revision ID: 0d3f4f0bd297
Revises: c2af8179a52d
Create Date: 2026-03-23 15:46:04.742492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d3f4f0bd297'
down_revision: Union[str, Sequence[str], None] = 'c2af8179a52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_index(op.f('user_name'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('user_name'), 'users', ['user_name'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
